const express = require('express');
const cors = require('cors');
const path = require('path');

const app = express();
app.use(cors());
app.use(express.json());

const profileData = {
  name: 'Jasmin Athuman Hatibu',
  email: 'jasmin@example.com',
  phone: '0621370679',
  module: 'Cloud Computing',
  assignmentTitle: 'Building and Deploying a Personal Portfolio Website Using Cloud Platforms',
  dueDate: '2/06/2026',
  description: 'This portfolio demonstrates frontend build, Vercel deployment, a simple backend API, and Render hosting.',
  profileImage: 'profile.jpg',
  skills: [
    { title: 'Frontend', detail: 'HTML, CSS, JavaScript' },
    { title: 'Cloud Hosting', detail: 'Vercel, Render' },
    { title: 'Backend', detail: 'Node.js, Express' },
    { title: 'Deployment', detail: 'Continuous deployment, API hosting' },
  ],
  projects: [
    { title: 'Personal Portfolio Site', description: 'A responsive portfolio website built for cloud deployment with Vercel and integrated with a backend API hosted on Render.' },
    { title: 'API Profile Service', description: 'A simple backend service that returns portfolio profile data in JSON for client applications.' },
  ],
};

app.get('/api/profile', (req, res) => {
  res.json(profileData);
});

app.post('/api/profile', (req, res) => {
  const allowedKeys = ['name', 'email', 'phone', 'module', 'assignmentTitle', 'dueDate', 'description', 'profileImage', 'skills', 'projects'];
  Object.keys(req.body).forEach((key) => {
    if (!allowedKeys.includes(key)) return;

    if (['skills', 'projects'].includes(key) && Array.isArray(req.body[key])) {
      profileData[key] = req.body[key].map((item) => ({ ...item }));
    } else if (typeof req.body[key] === 'string') {
      profileData[key] = req.body[key];
    }
  });

  res.json({ status: 'success', profile: profileData });
});

app.get('/admin', (req, res) => {
  // Serve an admin page generated by the backend so it always uses the
  // correct API base URL (useful when deployed on Render)
  const apiBase = `${req.protocol}://${req.get('host')}`;
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Portfolio Admin Page</title>
  <style>
    body { margin: 0; font-family: Inter, system-ui, sans-serif; background: #f4f7fb; color: #17212b; }
    .page { max-width: 960px; margin: 2rem auto; padding: 1rem; }
    .card { background: #ffffff; border: 1px solid #dce3ea; border-radius: 20px; padding: 1.75rem; box-shadow: 0 18px 40px rgba(22, 42, 77, 0.06); margin-bottom: 1.5rem; }
    h1, h2 { margin: 0 0 0.75rem; color: #1d2c55; }
    p { margin: 0 0 1rem; }
    label { display: block; margin: 1rem 0 0.5rem; font-weight: 600; }
    input, textarea { width: 100%; padding: 0.9rem 1rem; border: 1px solid #dce3ea; border-radius: 14px; font-size: 1rem; }
    textarea { min-height: 120px; resize: vertical; }
    button { margin-top: 1.5rem; padding: 0.9rem 1.25rem; border: none; background: #4066f5; color: white; border-radius: 14px; cursor: pointer; font-size: 1rem; }
    button:hover { background: #3452cc; }
    pre { white-space: pre-wrap; word-break: break-word; background: #f0f6ff; padding: 1rem; border-radius: 14px; border: 1px solid #dce3ea; }
    .status { margin-top: 1rem; color: #1a5b0b; }
    .link-row { display: flex; flex-wrap: wrap; gap: 1rem; margin-top: 1rem; }
    .link-row a { color: #4066f5; text-decoration: none; }
    .link-row a:hover { text-decoration: underline; }
  </style>
</head>
<body>
  <div class="page">
    <div class="card">
      <h1>Portfolio API Admin</h1>
      <p>This backend admin page lets you view and update the profile data that the frontend loads from the API.</p>
      <div class="link-row">
        <a href="/api/profile">View API JSON</a>
        <a href="/">Back to root</a>
      </div>
    </div>
    <div class="card">
      <h2>Current API Response</h2>
      <pre id="profileJson">Loading profile data...</pre>
    </div>
    <div class="card">
      <h2>Edit Profile Content</h2>
      <form id="profileForm">
        <label for="name">Name</label>
        <input id="name" name="name" type="text" />
        <label for="email">Email</label>
        <input id="email" name="email" type="email" />
        <label for="phone">Phone</label>
        <input id="phone" name="phone" type="text" />
        <label for="module">Module</label>
        <input id="module" name="module" type="text" />
        <label for="assignmentTitle">Assignment Title</label>
        <input id="assignmentTitle" name="assignmentTitle" type="text" />
        <label for="dueDate">Due Date</label>
        <input id="dueDate" name="dueDate" type="text" />
        <label for="description">Description</label>
        <textarea id="description" name="description"></textarea>
        <label for="skills">Skills (one per line, format: title: detail)</label>
        <textarea id="skills" name="skills" placeholder="Frontend: HTML, CSS, JavaScript\nCloud Hosting: Vercel, Render"></textarea>
        <label for="projects">Projects (one per line, format: title | description)</label>
        <textarea id="projects" name="projects" placeholder="Personal Portfolio Site | A responsive portfolio website...\nAPI Profile Service | Simple backend service..."></textarea>
        <label for="profileImage">Profile Image URL or relative path</label>
        <input id="profileImage" name="profileImage" type="text" />
        <button type="submit">Save Profile</button>
      </form>
      <div id="message" class="status"></div>
    </div>
  </div>
  <script>
    const apiBase = '${apiBase}';
    async function loadProfile() {
      try {
        const response = await fetch(`${apiBase}/api/profile`);
        const profile = await response.json();
        document.getElementById('profileJson').textContent = JSON.stringify(profile, null, 2);
        document.getElementById('name').value = profile.name || '';
        document.getElementById('email').value = profile.email || '';
        document.getElementById('phone').value = profile.phone || '';
        document.getElementById('module').value = profile.module || '';
        document.getElementById('assignmentTitle').value = profile.assignmentTitle || '';
        document.getElementById('dueDate').value = profile.dueDate || '';
        document.getElementById('description').value = profile.description || '';
        document.getElementById('skills').value = (profile.skills || []).map((s) => `${s.title}: ${s.detail}`).join('\n');
        document.getElementById('projects').value = (profile.projects || []).map((p) => `${p.title} | ${p.description}`).join('\n');
        document.getElementById('profileImage').value = profile.profileImage || '';
      } catch (err) {
        document.getElementById('profileJson').textContent = 'Unable to load profile: ' + err;
      }
    }
    function parseSkills(text) {
      return text.split('\n').map((line) => line.trim()).filter(Boolean).map((line) => {
        const [title, detail] = line.split(':').map((t) => t.trim());
        return { title: title || '', detail: detail || '' };
      });
    }
    function parseProjects(text) {
      return text.split('\n').map((line) => line.trim()).filter(Boolean).map((line) => {
        const parts = line.split('|').map((t) => t.trim());
        return { title: parts[0] || '', description: parts[1] || '' };
      });
    }
    document.getElementById('profileForm').addEventListener('submit', async (event) => {
      event.preventDefault();
      const payload = {
        name: document.getElementById('name').value,
        email: document.getElementById('email').value,
        phone: document.getElementById('phone').value,
        module: document.getElementById('module').value,
        assignmentTitle: document.getElementById('assignmentTitle').value,
        dueDate: document.getElementById('dueDate').value,
        description: document.getElementById('description').value,
        skills: parseSkills(document.getElementById('skills').value),
        projects: parseProjects(document.getElementById('projects').value),
        profileImage: document.getElementById('profileImage').value,
      };
      try {
        const response = await fetch(`${apiBase}/api/profile`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload),
        });
        const result = await response.json();
        document.getElementById('message').textContent = result.status === 'success' ? 'Profile updated successfully!' : 'Unable to save profile.';
        loadProfile();
      } catch (err) {
        document.getElementById('message').textContent = 'Error saving profile: ' + err;
      }
    });
    loadProfile();
  </script>
</body>
</html>`;

  res.setHeader('Content-Type', 'text/html');
  res.send(html);
});

app.get('/', (req, res) => {
  res.redirect('/admin');
});

const port = process.env.PORT || 3000;
app.listen(port, () => {
  console.log(`Backend running on http://localhost:${port}`);
});
